-- Create the table for storing triage reports
create table public.triage_reports (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Patient Info
  patient_name text,
  patient_age integer,
  
  -- Triage Info
  complaint text,
  symptoms_start text,
  pain_level integer,
  warning_signs text[], -- Array of strings
  
  -- Hanseniase Module
  hanseniase_active boolean default false,
  hanseniase_type text,
  neurite_acute boolean default false,
  lesion_details text,
  
  -- Final Classification
  classification_color text,
  technical_justification text,
  
  -- Metadata
  user_id text -- Phone number
);

-- Enable Row Level Security (RLS)
alter table public.triage_reports enable row level security;

-- Create a policy that allows anyone to insert (since it comes from n8n/webhook)
create policy "Enable insert for everyone" on public.triage_reports
  for insert with check (true);

-- Create a policy that allows anyone to read (for the dashboard)
-- In a real app, you would restrict this to admin users
create policy "Enable read for everyone" on public.triage_reports
  for select using (true);

-- Enable Realtime for this table
alter publication supabase_realtime add table public.triage_reports;
